### ISSUE TITLE
nso_action does not handle YANG model choice properly for input

### ISSUE THREAD

**Issue by gmuloc** [CiscoDevNet/ansible-nso#1]
This is in reference to this question that was raised on the NSO developer hub forum:
https://community.cisco.com/t5/nso-developer-hub-discussions/using-ansible-quot-nso-action-quot-module-to-invoke-quot-load/m-p/4173500

The following line validates that the input key is a YANG child in the schema of the input container but for a choice this is not correct and the correct input is being rejected:
https://github.com/CiscoDevNet/ansible-nso/blob/e6468dd20f3bb79288bbab8c27a8bf16c171ff2f/plugins/modules/nso_action.py#L109

**Comment by mamullen13316** [comment]
@gmuloc would you please post the Ansible playbook which returns the error? Thanks.

**Comment by gmuloc** [comment]
@mamullen13316 

```
- name: Load-Native Config
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Load variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: Load Native Config
    cisco.nso.nso_action:
      url: "{{ nso.url }}"
      username: "{{ nso.username }}"
      password: "{{ nso.password }}"
      path: /ncs:devices/ncs:device{f0}/load-native-config
      input: { file: "test.xml" }
```

using the same structure as in this repo - https://github.com/NSO-developer/nso-ansible-demo
